module.exports = {
	CLIENT_CONNECTED: "CLIENT_CONNECTED",
	NOTIFICATION_RECEIVED: "NOTIFICATION_RECEIVED",
	NOTIFICATION_MARK_READ: "NOTIFICATION_MARK_READ",
	NOTIFICATION_DELETED: "NOTIFICATION_DELETED",
	CLIENT_DISCONNECTED: "CLIENT_DISCONNECTED",
	LOGOOUT: "LOGOOUT"
}